export const list = [
	{
    id: 1,
    title: "High: Soar to New Heights| Ages:7+",
    author:"by Jess McGeachin   | 2 Feb 2023",
    price: 14.99,
    printlength: "64 pages",
    img: "https://m.media-amazon.com/images/I/41zXwUHR-LL._SX416_BO1,204,203,200_.jpg",
    amount: 1,
  },
{
    id: 2,
    title: "Engineering for Curious Kids: An Illustrated Introduction to Design, Building, Problem Solving | Ages:8-12",
    author:"by Chris Oxlade (Author), Alex Foster (Illustrator)   | 20 Jan 2023",
    price: 12.99,
    printlength: "128 pages",
    img: "https://m.media-amazon.com/images/I/51zwTBM+pQL._SX404_BO1,204,203,200_.jpg",
    amount: 1,
  },
{
    id: 3,
    title: "The Extraordinary Book that Invents Itself| Ages:6+",
    author:"by Alison Buxton (Author), Helen Bell (Author), Pintachan (Illustrator)  | 2 Feb 2023",
    price: 10.99,
    printlength: "64 pages",
    img: "https://m.media-amazon.com/images/I/51xiGKrLmOL._SX380_BO1,204,203,200_.jpg",
    amount: 1,
  },
{
    id: 4,
    title: "Marvel vs. DC: A Superhero Showdown (Versus) Library Binding  | Ages:10-13",
    author:"by Kenny Abdo  | 23 Jan 2023",
    price: 25.33,
    printlength: "24 pages",
    img: "https://m.media-amazon.com/images/I/511-4RpDy3L._SX347_BO1,204,203,200_.jpg",
    amount: 1,
  },
{
    id: 5,
    title: "Infinity: The Magical Cycles of the Universe (Cycles of the Universe): 1 | Ages:5-9",
    author:"by Soledad Romero Mariño (Author), Mariona Cabassa (Illustrator)| 27 Jan 	2023",
    price: 17.99,
	  printlength: "48 pages",
    img: "https://m.media-amazon.com/images/I/51DZMFEcitL._SX218_BO1,204,203,200_QL40_ML2	_.jpg",
    amount: 1,
  },
{
    id: 6,
    title: "Marvelous World of Magical Dragons: 3 (Klutz) Hardcover| Ages:8-12",
    author:"by Editors of Klutz  | 2 Feb 2023",
    price: 16.99,
	  printlength: "32 pages",
    img: "https://m.media-amazon.com/images/I/51s+BzqTxjL._SY498_BO1,204,203,200_.jpg",
    amount: 1,
  },
  {
    id: 7,
    title: "Meltdown: Discover Earth's Irreplaceable Glaciers and Learn What You Can Do to Save Them | Ages: 8-12",
    author: "by Anita Sanchez (Author), Lily Padula  | 24 Jan 2023",
    price: 15.99,
    printlength: "128 pages",
    img: "https://m.media-amazon.com/images/I/51hAMr90l5L._SX399_BO1,204,203,200_.jpg",
    amount: 1,
  },
 {
    id: 8,
    title: "Sleepy Sheepy Hardcover – Picture Book| Ages: 3-7",
    author:"by Lucy Ruth Cummins (Author), Pete Oswald (Illustrator) | 31 Jan 2023",
    price: 15.99,
	  printlength: "40 pages",
    img: "https://m.media-amazon.com/images/I/41mDlfaAUGL._SX480_BO1,204,203,200_.jpg",
    amount: 1,
  },
  {
    id: 9,
    title: "Visual Timelines: Science: Inventions and Discoveries Year by Year | Ages: 8-12",
    author: "by Anne Rooney (Author), Violet Tobacco (Illustrator)| 31 Jan. 2023",
    price: 14.99,
	  printlength: "128 pages",
    img: "https://m.media-amazon.com/images/I/51fQkexvQZL._SX404_BO1,204,203,200_.jpg",
    amount: 1,
  },

 {
    id: 10,
    title: "Jungle Junk: Re-Use, Recycle...Reimagine! | Ages: 6-11",
    author: "by Richard Turner (Author), Giulia Lombardo (Illustrator) | 1 Feb 2023",
    price: 14.25,
    printlength: "40 pages",
    img: "https://m.media-amazon.com/images/I/51q1EfW2kDL._SY410_BO1,204,203,200_.jpg",
    amount: 1,
  },

{
    id: 11,
    title: "Light (Start with Science) | Ages: 5-7",
    author: "by Charis Mather| 1 Feb 2023",
    price: 12.99,
    printlength: "24 pages",
    img: "https://m.media-amazon.com/images/I/51SIMbRMzVL._SY498_BO1,204,203,200_.jpg",
    amount: 1,
  },

{
    id: 12,
    title: "Our Planet: Created in partnership with WWF | Ages:	7-10",
    author: "by Matt Whyman (Author), Richard Jones (Illustrator), Sir David Attenborough (Foreword)| 2 Feb 2023",
    price: 12.99,
    printlength: "96 pages",
    img: "https://m.media-amazon.com/images/I/51TK3waVjBL._SX355_BO1,204,203,200_.jpg",
    amount: 1,
  },

];